/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package javavideoclub;

import java.awt.Color;

import java.awt.*;
import javax.swing.*;
import javax.swing.table.*;
import java.sql.*;
import java.util.*;
import java.applet.*;
import java.text.*;
import java.time.*;
import java.beans.*;
import java.io.*;
import java.math.*;
import java.lang.*;
import java.net.*;
import java.nio.*;

/**
 *
 * @author pc
 */
public class ConnexionAdminInterface extends javax.swing.JFrame {

    /** Creates new form ConnexionAdmin */
    public ConnexionAdminInterface() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        voirIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numeroOuEmailField = new javax.swing.JTextField();
        mdpField = new javax.swing.JTextField();
        okBtn = new javax.swing.JButton();
        annulerBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        compteNonExistantLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Video Club : Connexion");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(860, 560));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 252, 252));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Numero de telephone ou Email :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, 49));

        voirIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        voirIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vidClub/eye icon.png"))); // NOI18N
        voirIcon.setEnabled(false);
        voirIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voirIconMouseClicked(evt);
            }
        });
        jPanel1.add(voirIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, 40, 40));
        Icon voirIconI = voirIcon.getIcon();
        ImageIcon iconImage = (ImageIcon)voirIconI;
        Image img = iconImage.getImage().getScaledInstance(30, 30,Image.SCALE_SMOOTH);
        voirIcon.setIcon(new ImageIcon(img));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Connexion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 120, 66));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Mot de passe :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 209, 50));

        numeroOuEmailField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numeroOuEmailFieldKeyTyped(evt);
            }
        });
        jPanel1.add(numeroOuEmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 350, 49));

        mdpField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mdpFieldKeyTyped(evt);
            }
        });
        jPanel1.add(mdpField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 350, 50));
        mdpField.setVisible(false);

        okBtn.setBackground(new java.awt.Color(153, 115, 153));
        okBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        okBtn.setText("OK");
        okBtn.setEnabled(false);
        okBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okBtnMouseClicked(evt);
            }
        });
        jPanel1.add(okBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 393, 106, 48));

        annulerBtn.setBackground(new java.awt.Color(153, 115, 153));
        annulerBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        annulerBtn.setText("Annuler");
        annulerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                annulerBtnMouseClicked(evt);
            }
        });
        jPanel1.add(annulerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 393, 100, 48));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 140, 20));

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, 40, 20));

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 50, 20));

        compteNonExistantLabel.setForeground(new java.awt.Color(255, 51, 51));
        compteNonExistantLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        compteNonExistantLabel.setText("   ");
        jPanel1.add(compteNonExistantLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 350, -1));

        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordFieldKeyTyped(evt);
            }
        });
        jPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 350, 50));

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 220, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void annulerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_annulerBtnMouseClicked
        // TODO add your handling code here:
        numeroOuEmailField.setText("");
        mdpField.setText("");
    }//GEN-LAST:event_annulerBtnMouseClicked

    private void okBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okBtnMouseClicked
        // TODO add your handling code here:
        okBtn.setEnabled(enabledOrNot());
        if (okBtn.isEnabled()){
            Admin quiSeConnecte = new Admin();
            quiSeConnecte.setEmail(numeroOuEmailField.getText().trim());
            quiSeConnecte.setNumeroDeTelephone(numeroOuEmailField.getText().trim());
            if (mdpField.isVisible()) {
                quiSeConnecte.setMdp(mdpField.getText().trim());
            }
            else if (passwordField.isVisible()){
                quiSeConnecte.setMdp(new String(passwordField.getPassword()));    
            }
            quiSeConnecte.seConnecter();
            if (quiSeConnecte.getCompteExiste()) {
                dispose ();
                FilmsInterface frame = new FilmsInterface();
                frame.setVisible(true);
            } else {compteNonExistantLabel.setText("Ce compte n'existe pas. Veuiller reverifier.");}
        } else { okBtn.setEnabled(enabledOrNot()); }
    }//GEN-LAST:event_okBtnMouseClicked

    private void numeroOuEmailFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroOuEmailFieldKeyTyped
        // TODO add your handling code here:
        if (enabledOrNot()) {
            okBtn.setBackground(Color.decode("#997399"));
            okBtn.setEnabled(enabledOrNot());
        } else {okBtn.setEnabled(enabledOrNot());}
    }//GEN-LAST:event_numeroOuEmailFieldKeyTyped

    private void mdpFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mdpFieldKeyTyped
        // TODO add your handling code here:
        if (enabledOrNot()) {
            okBtn.setBackground(Color.decode("#997399"));
            okBtn.setEnabled(enabledOrNot());
        } else {okBtn.setEnabled(enabledOrNot());}
    }//GEN-LAST:event_mdpFieldKeyTyped

    private void voirIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voirIconMouseClicked
        if (!mdpField.isVisible()) {
            mdpField.setText(new String(passwordField.getPassword()));
            mdpField.setVisible(true);
            passwordField.setVisible(false);
            mdpField.requestFocus();
        }
        else if (mdpField.isVisible()){
            passwordField.setText(mdpField.getText());
            mdpField.setVisible(false);
            passwordField.setVisible(true);
            passwordField.requestFocus();
        }
        if (!voirIcon.isEnabled()) {
            voirIcon.setEnabled(true);
        } else if (voirIcon.isEnabled()) { 
            voirIcon.setEnabled (false);
        }
    }//GEN-LAST:event_voirIconMouseClicked

    private void passwordFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyTyped
        if (enabledOrNot()) {
            okBtn.setBackground(Color.decode("#997399"));
            okBtn.setEnabled(enabledOrNot());
        } else {okBtn.setEnabled(enabledOrNot());}
    }//GEN-LAST:event_passwordFieldKeyTyped
    
    private Boolean enabledOrNot () {
        if (numeroOuEmailField.getText().trim().isEmpty()) {
            return false;
        }
        if (mdpField.isVisible()){
            if (mdpField.getText().trim().isEmpty()) {
                return false;
            }
            else {
                return true;
            }
        }
        else if (passwordField.isVisible()) {
            if (new String (passwordField.getPassword()).trim().isEmpty()) {
                return false;
            }
            else {
                return true;
            }
        }
        else {   
            return true;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConnexionAdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConnexionAdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConnexionAdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConnexionAdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConnexionAdminInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annulerBtn;
    private javax.swing.JLabel compteNonExistantLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField mdpField;
    private javax.swing.JTextField numeroOuEmailField;
    private javax.swing.JButton okBtn;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel voirIcon;
    // End of variables declaration//GEN-END:variables

}
